### ISSUE TITLE
Multipeer module isn't imported in library script

### ISSUE THREAD

**Issue by positlabs** [facebookincubator/spark-state#10]
The multipeer module fails to import in spark-state. I have to manually import in my script, even if I'm not using the module directly.

`const Multipeer = require('Multipeer')`

Without it, I get this uncaught promise warning:

```
WARNING: Possible Unhandled Promise Rejection: TypeError: Cannot read property 'getBinaryMessageChannel' of undefined
   {
     "line": 27,
     "column": 52,
     "sourceURL": "global_signal.js"
   }
```

Which points to this line: https://github.com/facebookincubator/spark-state/blob/main/src/global_signal.js#L27

`const channel = Multipeer.getBinaryMessageChannel(signalName)`

**Comment by positlabs** [comment]
I see this is actually mentioned in the docs, but it took me a while to figure out what was happening because the error message isn't very helpful. 

https://github.com/facebookincubator/spark-state#loading-the-module

A simple solution would be to include a message if `Multipeer` is undefined

```
const Multipeer = require('Multipeer')
if(Multipeer === undefined) throw Error(`You must import the Multipeer module to use spark-state. Add "const Multipeer = require('Multipeer')" to your script`)
```

**Comment by zhang123cnn** [comment]
@positlabs Thanks for reporting this issue! Yes, we should make the error message more clear. We are planning to improve Spark AR Studio to auto-add needed capabilities from scripting library. So hopefully this will not be an issue soon.
