### ISSUE TITLE
Missing all functions

### ISSUE THREAD

**Issue by positlabs** [facebookincubator/spark-state#29]
I tried using spark-state in v137 and v138 but I'm getting this error message: "TypeError: undefined is not a function" when I try to use any of the methods from spark-state. I've had this message before when there was a missing capability, but I can see the functions are there if I iterate on the State object. 

```
const Multipeer = require('Multipeer')
const State = require('spark-state')
for(var i in State) {
  log(i)
  log(`${State[i]}: typeof ${typeof State[i]}`)
  State[i]('asdf', 'asdfasd')
}
log(State)

log(typeof State['createCounterGlobalSignal'])
State['createCounterGlobalSignal'](1, 'globalCounter')
```

<img width="739" alt="Screen Shot 2022-05-25 at 5 22 12 PM" src="https://user-images.githubusercontent.com/1918844/170369565-6c3870c7-2693-4f2d-92cd-8555495e47f6.png">

I'm super confused about what is happening. The functions are there, but they aren't?

**Comment by zhang123cnn** [comment]
Hey @positlabs thanks for sharing your feedback with us.

QQ Have you added Participants module to your script and added “Scripting Writeable Signal Source” capability? 

(Detailed instruction at https://github.com/facebookincubator/spark-state#spark-ar-project-setup)

These capabilities are used further in the code base so you may still be able to print State even though it would fail later.

please let me know if that resolve your issue. Happy to help further

**Comment by positlabs** [comment]
Ahhh, yeah it's working now! Thanks!

Another thing that tripped me up a bit was the examples. Seems like they are all misformatted in a similar way. 

`    const globalString = await State.creatStringGlobalSignal('Hello', 'globalString');`

**Comment by positlabs** [comment]
Is there some way to detect if "Scripting Writeable Signal Source" has been enabled? I want to add a catch to my code in case this happens.

**Comment by positlabs** [comment]
This seems like it should work. 

```
if(typeof Multipeer === 'undefined') log('Import the Multipeer module to use spark-state')
State.createGlobalStringSignal('', 'checkCapabilities').catch(e => {log('Failed to create global signal. Ensure Scripting Writeable Signal Source is added to your project capabilities')})
```

**Comment by zhang123cnn** [comment]
I think it would be hacky to check that. However we are planning a project to auto add required capabilities once a scripting library is imported. So hopefully in the near future this manual adding capabilities would not be needed. Please stay tuned on that.
